== 동시성 테스트 프로젝트

동시성과 병렬성의 차이에 대해 알아보는 Demo 프로젝트

=== 동시성

동시성에 대해 쉽게 간단히 설명하자면, 2개의 일을 처리해야 할 때 +
A와 B가 병렬로 처리되는 것 처럼 보이지만 +
실질적으로 A가 작업을 할 때, B는 쉬고 +
B가 작업을 할 때 A는 쉬면서 작업이 진행 된다.

우리가 내부적으로 들여다 보지 않을 때는 이게 동시에 처리되는 것처럼 보일 뿐이다.

예시를 들자면, 한 명의 쉐프가 된장찌개와 김치찌개 주문을 받았을 때, +
된장찌개와 김치찌개를 함께 조리한다고 볼 수도 있을 것 같다.

이때 정확히 말하자면, 된장찌개와 김치찌개의 재료가 완전 상이하다고 가정

된장찌개에 들어가는 채소를 썰 때는, 전혀 김치찌개에 대한 조리를 할 수 없다. +
또한 된장찌개 들어가는 채소를 다 썰고, 김치찌개에 대한 채소를 썰 때는 된장찌개에 대한 조리를 할 수 없다.

김치찌개에 대한 조리를 할 때는, 된장찌개 조리를 할 수없고, 된장찌개는 요리가 되기를 기다릴 수 밖에 없다~

'''

여기서 A가 처리하던 일을 멈추고, B가 다시 일을 처리하기 시작하고 할 때
Context Switching 이 일어난다고 하는 것임.

=== 병렬성

병렬성이란, 말 그대로 2개의 일을 처리할 때, +
A와 B가 서로에 작업에 전혀 관계하지 않고, +
A는 A대로 일을 처리하고, B는 B대로 일을 처리하는 것이다.

예로, 두 명의 쉐프가 된장찌개와 김치찌개 주문을 받았을 때, +
동시에 한 명은 된장찌개 조리를 하고, 다른 한 명은 김치찌개 조리를 하면 된다.

김치찌개가 된장찌개의 조리가 끝나길 기다릴 필요가 전혀 없게 된다. 된장찌개 또한 마찬가지..

'''

Rob Pike 가 지적했다고 한답니다. +
동시성은 한 번에 많은 것을 처리하는 것이고 +
병렬성은 한 번에 많은 작업을 수행하는 것!



> 단일 코어 CPU에서는 동시성을 가질 수 있지만, 병렬성은 가질 수 없다.

'''

=== Multi Threading
일반적으로 단일 CPU는 여러 스레드 간에 실행시간을 공유하여 지정된 시간 동안 각 스레드 사이를 switching 함. +
Application의 Thread를 다른 CPU에서 사용하는 것도 가능함.

=== CPU core 수 확인

[source,shell]
----
sysctl hw.physicalcpu hw.logicalcpu
----

MacBook의 Core 를 GUI를 통해서 확인하면 다음과 같다.
*프로세서* 2.3 GHz 8코어 Intel Core i9

*내 MacBook 의 결과*

----
hw.physicalcpu: 8
hw.logicalcpu: 16
----

=== JVM CPU Core 수 조정
아래 옵션은 JAVA Advanced(고급) Runtime Option이다. +
`-XX:ActiveProcessorCount=x` +
VM이 GarbageCollection 및 ForkJoinPool 과 같은 다양한 작업에 사용할 스레드 풀의 크기를 계산하는데 사용할 CPU 수 재정의 +

> 여기서 생각할 것, ForkJoinPool이란? +
GarbageCollection 과 ForkJoinPool 에만 영향을 끼치는 것인가? +

참고지만, 도커 컨테이너에서 여러 Java 프로세세스를 실행할 때 CPU 리소스를 분할는데 유용하게 사용. +

실제 해당 옵션을 주고 아래 코드를 실행해 보자.
----
-XX:ActiveProcessorCount=1
----
----
    public static void main(String[] args) {
        System.out.println(">>>>> runtime availableProcessors :: " + Runtime.getRuntime().availableProcessors());
    }
----
결과
----
>>>>> runtime availableProcessors :: 1
----


참고 : https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE

=== AtomicInteger
AtomicIntegerDemo 클래스에서 테스트..

Counter 클래스를 두개 만들었는데, 루프를 20번 돌아서, 20이 출력되어야 원하는 결과라고 볼 수 있음. +
하지만, AtomicInteger를 사용하지 않고, int를 사용한 클래스의 경우, 20보다 작은 수가 출력되는 걸 볼 수 있음. +

