== 동시성 테스트 프로젝트

동시성과 병렬성의 차이에 대해 알아보는 Demo 프로젝트

=== 동시성

동시성에 대해 쉽게 간단히 설명하자면, 2개의 일을 처리해야 할 때 +
A와 B가 병렬로 처리되는 것 처럼 보이지만 +
실질적으로 A가 작업을 할 때, B는 쉬고 +
B가 작업을 할 때 A는 쉬면서 작업이 진행 된다.

우리가 내부적으로 들여다 보지 않을 때는 이게 동시에 처리되는 것처럼 보일 뿐이다.

예시를 들자면, 한 명의 쉐프가 된장찌개와 김치찌개 주문을 받았을 때, +
된장찌개와 김치찌개를 함께 조리한다고 볼 수도 있을 것 같다.

이때 정확히 말하자면, 된장찌개와 김치찌개의 재료가 완전 상이하다고 가정

된장찌개에 들어가는 채소를 썰 때는, 전혀 김치찌개에 대한 조리를 할 수 없다. +
또한 된장찌개 들어가는 채소를 다 썰고, 김치찌개에 대한 채소를 썰 때는 된장찌개에 대한 조리를 할 수 없다.

김치찌개에 대한 조리를 할 때는, 된장찌개 조리를 할 수없고, 된장찌개는 요리가 되기를 기다릴 수 밖에 없다~

'''

여기서 A가 처리하던 일을 멈추고, B가 다시 일을 처리하기 시작하고 할 때
Context Switching 이 일어난다고 하는 것임.

=== 병렬성

병렬성이란, 말 그대로 2개의 일을 처리할 때, +
A와 B가 서로에 작업에 전혀 관계하지 않고, +
A는 A대로 일을 처리하고, B는 B대로 일을 처리하는 것이다.

예로, 두 명의 쉐프가 된장찌개와 김치찌개 주문을 받았을 때, +
동시에 한 명은 된장찌개 조리를 하고, 다른 한 명은 김치찌개 조리를 하면 된다.

김치찌개가 된장찌개의 조리가 끝나길 기다릴 필요가 전혀 없게 된다. 된장찌개 또한 마찬가지..

'''

Rob Pike 가 지적했다고 한답니다. +
동시성은 한 번에 많은 것을 처리하는 것이고 +
병렬성은 한 번에 많은 작업을 수행하는 것!



> 단일 코어 CPU에서는 동시성을 가질 수 있지만, 병렬성은 가질 수 없다.

'''

=== Multi Threading
일반적으로 단일 CPU는 여러 스레드 간에 실행시간을 공유하여 지정된 시간 동안 각 스레드 사이를 switching 함. +
Application의 Thread를 다른 CPU에서 사용하는 것도 가능함.

=== CPU core 수 확인

[source,shell]
----
sysctl hw.physicalcpu hw.logicalcpu
----

MacBook의 Core 를 GUI를 통해서 확인하면 다음과 같다.
*프로세서* 2.3 GHz 8코어 Intel Core i9

*내 MacBook 의 결과*

----
hw.physicalcpu: 8
hw.logicalcpu: 16
----

=== JVM CPU Core 수 조정
아래 옵션은 JAVA Advanced(고급) Runtime Option이다. +
`-XX:ActiveProcessorCount=x` +
VM이 GarbageCollection 및 ForkJoinPool 과 같은 다양한 작업에 사용할 스레드 풀의 크기를 계산하는데 사용할 CPU 수 재정의 +

> 여기서 생각할 것, ForkJoinPool이란? +
GarbageCollection 과 ForkJoinPool 에만 영향을 끼치는 것인가? +

참고지만, 도커 컨테이너에서 여러 Java 프로세세스를 실행할 때 CPU 리소스를 분할는데 유용하게 사용. +

실제 해당 옵션을 주고 아래 코드를 실행해 보자.
----
-XX:ActiveProcessorCount=1
----
----
    public static void main(String[] args) {
        System.out.println(">>>>> runtime availableProcessors :: " + Runtime.getRuntime().availableProcessors());
    }
----
결과
----
>>>>> runtime availableProcessors :: 1
----


참고 : https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE

=== AtomicInteger
AtomicIntegerDemo 클래스에서 테스트..

Counter 클래스를 두개 만들었는데, 루프를 20번 돌아서, 20이 출력되어야 원하는 결과라고 볼 수 있음. +
하지만, AtomicInteger를 사용하지 않고, int를 사용한 클래스의 경우, 20보다 작은 수가 출력되는 걸 볼 수 있음. +

'''

=== ThreadLocal

아래와 같은 코드가 있을 때 어떤 결과가 나올?

[source,java]
----
public static void main(String[] args) throws InterruptedException {
    System.out.println(">>>>> runtime availableProcessors :: " + Runtime.getRuntime().availableProcessors());
    final ThreadLocalCounter counter = new ThreadLocalCounter();
    final Thread t1 = new Thread(counter, "t1");
    final Thread t2 = new Thread(counter, "t2");
    t1.start();
    t2.start();
}
// ...
class ThreadLocalCounter implements Runnable {
    private static final int START_INDEX = 0;
    private static final int END_INDEX = 10;

    private ThreadLocal<Integer> count = new ThreadLocal<>();

    public ThreadLocalCounter() {
        count.set(0);
    }

    @SneakyThrows
    @Override
    public void run() {

        for (int i = START_INDEX; i < END_INDEX; i++) {
            count.set(count.get() + 1);
        }
        printThreadWithCount(Thread.currentThread());
    }

    private void printThreadWithCount(Thread thread) {
        System.out.println(">>>>> " + thread.getName() + " - count : " + getCount());
    }

    public int getCount() {
        return count.get();
    }
}
----

결과는 다음과 같다.

----
Exception in thread "t2" Exception in thread "t1" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.ThreadLocal.get()" is null
----

> 참고로 MAIN Thread의 우선수위는 5

이유인 즉슨, main Thread가 ThreadLocal변수를 0으로 set 하였고, +
Thread t1, t2는 main Thread가 초기화 한 ThreadLocal 변수에 영향을 받지 않았기 때문에, +
t1, t2 Thread의 ThreadLocal 변수는 null인 상태인 것이다.

아래의 코드로 변경하면 t1, t2 쓰레드는 동일한 결과를 출력하게 된다
.
[source, java]
----
// main method는 동일

// ...

class ThreadLocalCounter implements Runnable {
    private static final int START_INDEX = 0;
    private static final int END_INDEX = 10;

    private ThreadLocal<Integer> count = new ThreadLocal<>();

    @SneakyThrows
    @Override
    public void run() {

        if (START_INDEX == 0) count.set(0);

        for (int i = START_INDEX; i < END_INDEX; i++) {
            count.set(count.get() + 1);
        }
        printThreadWithCount(Thread.currentThread());
    }

    private void printThreadWithCount(Thread thread) {
        System.out.println(">>>>> " + thread.getName() + " - count : " + getCount());
    }

    public int getCount() {
        return count.get();
    }
}
----
결과
[source, script]
----
>>>>> runtime availableProcessors :: 1
>>>>> t1 - count : 10
>>>>> t2 - count : 10
----

=== volatile

CPU는 초당 많은 명령을 수행할 수 있으므로, RAM에서 가져오는 것은 그다지 이상적이 않음 +
이 상황을 개선하기 위해 프로세서는 Out of Order Execution, Branch Prediction, Speculative Execution 및 Caching과 같은 트릭을 사용하고 있다

간단히 말해, 하나의 스레드가 캐시된 값을 업데이트 할 때 어떤 일이 발생하는지 두 번 생각해야 한다.

==== 언제 Volatile 을 사용하나?

**Thread.yield** +
현재 Thread가 프로세서의 현재 사용을 양보할 의향이 있다는 스케줄러에 대한 힌트 +
스케줄러는 이 힌트를 무시해도 됨

현재 주어진, com.example.concurrency.pojo.volatiles 코드로는 와닿지 않음

'''

volatile 은 원자성이 아닌 가시성을 보장 +
synchronization 은 원자성 및 가시성 보장 +
volatile 은 synchronization 을 대체할 수 없음 +
volatile 은 재정렬하지 않도록 함 +
데이터가 둘 이상의 스레드에서 액세스할 수 있고 잠금으로 보호되지 않으며 메모리 액세스 순서에 의존하는 전역 메모리를 참조하는 경우 +
volatile을 사용하는 것이 lock을 사용하는 것 보다 저렴하다.

volatile은 메인 메모리에 쓰고 메인 메모리에서 읽어 온다. 테스트 결과 1억번의 루프를 돌린 경우 +
단순 count 증가 코드 한줄. +
volatile을 선언하면 437 밀리세컨드의 시간이 걸리고 volatile을 선언하지 않으면 +
CPU Cache에서 읽어올 수 있다(항상 그런 것은 아님) 6밀리세컨드의 시간이 걸린다. +
volatile은 main memory에서 값을 읽어 오기 때문에 멀티코어 프로세서에서 가시성이 보장된다. +
여기서 가시성이란 최종 변경된 값을 읽어 오느냐... +
CPU2개로 나뉘어져 있는 경우 2개의 쓰레드가 다른 CPU Core에서 실행됐을 때 +
각 CPU에 존재하는 CPU Cache에서 값을 읽어 오는 경우 +
서로 다른 값을 가지고 오는 문제가 발생할 수 있다.

**_TODO_** 여기서, volatile을 사용하는 것이 왜 lock을 사용하는 것 보다 저렴한지 알아야 함