== 동시성 테스트 프로젝트

동시성과 병렬성의 차이에 대해 알아보는 Demo 프로젝트

=== 동시성

동시성에 대해 쉽게 간단히 설명하자면, 2개의 일을 처리해야 할 때 +
A와 B가 병렬로 처리되는 것 처럼 보이지만 +
실질적으로 A가 작업을 할 때, B는 쉬고 +
B가 작업을 할 때 A는 쉬면서 작업이 진행 된다.

우리가 내부적으로 들여다 보지 않을 때는 이게 동시에 처리되는 것처럼 보일 뿐이다.

예시를 들자면, 한 명의 쉐프가 된장찌개와 김치찌개 주문을 받았을 때, +
된장찌개와 김치찌개를 함께 조리한다고 볼 수도 있을 것 같다.

이때 정확히 말하자면, 된장찌개와 김치찌개의 재료가 완전 상이하다고 가정

된장찌개에 들어가는 채소를 썰 때는, 전혀 김치찌개에 대한 조리를 할 수 없다. +
또한 된장찌개 들어가는 채소를 다 썰고, 김치찌개에 대한 채소를 썰 때는 된장찌개에 대한 조리를 할 수 없다.

김치찌개에 대한 조리를 할 때는, 된장찌개 조리를 할 수없고, 된장찌개는 요리가 되기를 기다릴 수 밖에 없다~

'''

여기서 A가 처리하던 일을 멈추고, B가 다시 일을 처리하기 시작하고 할 때
Context Switching 이 일어난다고 하는 것임.

=== 병렬성

병렬성이란, 말 그대로 2개의 일을 처리할 때, +
A와 B가 서로에 작업에 전혀 관계하지 않고, +
A는 A대로 일을 처리하고, B는 B대로 일을 처리하는 것이다.

예로, 두 명의 쉐프가 된장찌개와 김치찌개 주문을 받았을 때, +
동시에 한 명은 된장찌개 조리를 하고, 다른 한 명은 김치찌개 조리를 하면 된다.

김치찌개가 된장찌개의 조리가 끝나길 기다릴 필요가 전혀 없게 된다. 된장찌개 또한 마찬가지..

'''

Rob Pike 가 지적했다고 한답니다. +
동시성은 한 번에 많은 것을 처리하는 것이고 +
병렬성은 한 번에 많은 작업을 수행하는 것!



> 단일 코어 CPU에서는 동시성을 가질 수 있지만, 병렬성은 가질 수 없다.

'''

=== CPU core 수 확인

[source,shell]
----
sysctl hw.physicalcpu hw.logicalcpu
----

MacBook의 Core 를 GUI를 통해서 확인하면 다음과 같다.
*프로세서* 2.3 GHz 8코어 Intel Core i9

*내 MacBook 의 결과*

----
hw.physicalcpu: 8
hw.logicalcpu: 16
----